apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: quantflow
  labels:
    app: quantflow-backend
spec:
  type: ClusterIP
  selector:
    app: quantflow-backend
  ports:
    - port: 8000
      targetPort: 8000
      name: http
